In [1]:
import numpy as np
def create_custom_vectors():
    while True:
        num_vectors = int(input("Ingrese el número de vectores (entre 3 y 5): "))
        if 3 <= num_vectors <= 5:
            break
        else:
            print("Número no válido. Solo se permiten valores entre 3 y 5.")
    size = int(input("Ingrese el tamaño de los vectores: "))
    
    vectors = []
    for i in range(num_vectors):
        vector = []
        print(f"Ingrese los elementos del vector {i+1} (solo se permiten valores de 1 o -1):")
        for j in range(size):
            while True:
                value = int(input(f"Elemento {j+1}: "))
                if value in [-1, 1]:
                    vector.append(value)
                    break
                else:
                    print("Valor no válido. Solo se permiten valores de 1 o -1.")
        vectors.append(np.array(vector))
    return vectors

# Genera los vectores personalizados
vectors = create_custom_vectors()



Ingrese los elementos del vector 1 (solo se permiten valores de 1 o -1):
Ingrese los elementos del vector 2 (solo se permiten valores de 1 o -1):
Ingrese los elementos del vector 3 (solo se permiten valores de 1 o -1):


Vectores generados:  [ 1  1 -1]


In [16]:

# Realiza la operación de producto punto en los vectores generados
results = []
for vector in vectors:
    At = vector[:, np.newaxis]
    result = np.dot(At, vector[np.newaxis, :])
    results.append(result)



In [17]:
# Suma los resultados de los productos punto
Pesos = np.sum(results, axis=0)

# Imprime los vectores generados y los resultados de las operaciones
for i, vector in enumerate(vectors):
    print(f"Vector {i+1}: {vector}")

for i, result in enumerate(results):
    print(f"Resultado {i+1}:\n{result}")

# Imprime la suma de los resultados
print(f"Suma de los resultados (Pesos):\n{Pesos}")

Vector 1: [1 1 1 1]
Vector 2: [ 1 -1 -1 -1]
Vector 3: [ 1  1 -1 -1]
Resultado 1:
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
Resultado 2:
[[ 1 -1 -1 -1]
 [-1  1  1  1]
 [-1  1  1  1]
 [-1  1  1  1]]
Resultado 3:
[[ 1  1 -1 -1]
 [ 1  1 -1 -1]
 [-1 -1  1  1]
 [-1 -1  1  1]]
Suma de los resultados (Pesos):
[[ 3  1 -1 -1]
 [ 1  3  1  1]
 [-1  1  3  3]
 [-1  1  3  3]]


In [18]:

# Copia la matriz Pesos y establece la diagonal en ceros
P_1 = np.copy(Pesos)
np.fill_diagonal(P_1, 0)

# Imprime la matriz con la diagonal en ceros
print(f"Pesos con la diagonal en ceros (P_1):\n{P_1}")

Pesos con la diagonal en ceros (P_1):
[[ 0  1 -1 -1]
 [ 1  0  1  1]
 [-1  1  0  3]
 [-1  1  3  0]]


In [ ]:
import numpy as np

def create_custom_vectors():
    while True:
        num_vectors = int(input("Ingrese el número de vectores (entre 3 y 5): "))
        if 3 <= num_vectors <= 5:
            break
        else:
            print("Número no válido. Solo se permiten valores entre 3 y 5.")
    
    size = int(input("Ingrese el tamaño de los vectores: "))
    
    vectors = []
    for i in range(num_vectors):
        vector = []
        print(f"Ingrese los elementos del vector {i+1} (solo se permiten valores de 1 o -1):")
        for j in range(size):
            while True:
                value = int(input(f"Elemento {j+1}: "))
                if value in [-1, 1]:
                    vector.append(value)
                    break
                else:
                    print("Valor no válido. Solo se permiten valores de 1 o -1.")
        vectors.append(np.array(vector))
    
    return vectors

# Genera los vectores personalizados
vectors = create_custom_vectors()

# Realiza la operación de producto punto en los vectores generados
results = []
for vector in vectors:
    At = vector[:, np.newaxis]
    result = np.dot(At, vector[np.newaxis, :])
    results.append(result)

# Suma los resultados de los productos punto
Pesos = np.sum(results, axis=0)

# Imprime los vectores generados y los resultados de las operaciones
for i, vector in enumerate(vectors):
    print(f"Vector {i+1}: {vector}")

for i, result in enumerate(results):
    print(f"Resultado {i+1}:\n{result}")

# Imprime la suma de los resultados
print(f"Suma de los resultados (Pesos):\n{Pesos}")

# Copia la matriz Pesos y establece la diagonal en ceros
P_1 = np.copy(Pesos)
np.fill_diagonal(P_1, 0)

# Imprime la matriz con la diagonal en ceros
print(f"Pesos con la diagonal en ceros (P_1):\n{P_1}")



# Multiplica la matriz P_1 por cada vector de entrada
multiplication_results = []
for i, vector in enumerate(vectors):
    multiplication_result = np.dot(P_1, vector)
    multiplication_results.append(multiplication_result)
    print(f"Multiplicación de P_1 por el vector {i+1}:\n{multiplication_result}")



