In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler, Normalizer
from sklearn.metrics import accuracy_score
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.metrics import classification_report

In [3]:
# Preparación de los datos
from sklearn import preprocessing
# Cargar los datos desde el archivo CSV
data = pd.read_csv("HOG_TODO.csv")

# Dividir los datos en características (features) y etiquetas (labels)
X = data.drop("etiqueta", axis=1)  # Características
y = data["etiqueta"]  # Etiquetas

In [4]:
# Escalar las características
# norma = Normalizer()
# X_train_scaled = preprocessing.normalize(X_train)
# X_test_scaled = preprocessing.normalize(X_test)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


In [13]:
learning_rate = 0.20 # Tasa de aprendizaje
momentum_descent = 0.40  # Momentum
hidden_layers = (15)  # Número de capas ocultas y número de neuronas en cada capa
validation = 0.1  # Porcentaje de particiones para validación (0.1 = 10%  => 10 folds)

from sklearn.model_selection import cross_val_score

# Crear el clasificador MLP
mlp_classifier = MLPClassifier(
                        max_iter = 1000,
                        activation = 'relu',
                        solver= 'adam',
                        random_state=11,
                        tol = 1e-3,
                        validation_fraction = validation,
                        hidden_layer_sizes = hidden_layers,
                        learning_rate_init = learning_rate,
                        momentum = momentum_descent,
                        )

from sklearn.model_selection import cross_val_predict
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
for i in range(3, 21): 
    y_pred = cross_val_predict(mlp_classifier, X_scaled, y, cv=i)
    accuracy = accuracy_score(y, y_pred)
    print(f"Fold: {i} -> Accuracy: {accuracy}")

Fold: 3 -> Accuracy: 0.7255555555555555
Fold: 4 -> Accuracy: 0.7233333333333334
Fold: 5 -> Accuracy: 0.7311111111111112
Fold: 6 -> Accuracy: 0.7233333333333334
Fold: 7 -> Accuracy: 0.7277777777777777
Fold: 8 -> Accuracy: 0.7433333333333333
Fold: 9 -> Accuracy: 0.7477777777777778
Fold: 10 -> Accuracy: 0.7444444444444445
Fold: 11 -> Accuracy: 0.7277777777777777
Fold: 12 -> Accuracy: 0.7177777777777777
Fold: 13 -> Accuracy: 0.7522222222222222
Fold: 14 -> Accuracy: 0.7355555555555555
Fold: 15 -> Accuracy: 0.74
Fold: 16 -> Accuracy: 0.7155555555555555
Fold: 17 -> Accuracy: 0.7111111111111111
Fold: 18 -> Accuracy: 0.7411111111111112
Fold: 19 -> Accuracy: 0.7122222222222222
Fold: 20 -> Accuracy: 0.7233333333333334


In [14]:
y_pred = cross_val_predict(mlp_classifier, X_scaled, y, cv=13)

precision = precision_score(y, y_pred, average='weighted') 
recall = recall_score(y, y_pred, average='weighted') 
f1 = f1_score(y, y_pred, average='weighted')

print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")

conf_mat = confusion_matrix(y, y_pred)
print(conf_mat)

Precision: 0.7541367966529191
Recall: 0.7522222222222222
F1 Score: 0.7524214934352608
[[216  31  53]
 [ 43 224  33]
 [ 41  22 237]]
