In [44]:
import numpy as np


def create_random_vector(size, vectors):
    
    vectores_f = []

    for i in range(vectors):
        vectores = np.random.choice([-1, 1], size=size)
        vectores_f.append(vectores)
    
    return vectores_f

size = 3
vectors = 2

vectores_f = create_random_vector(size, vectors)

for i in range(len(vectores_f)):
    print(vectores_f[i])

[-1 -1 -1]
[-1  1 -1]


In [45]:
transpuestas = []
for i in range(len(vectores_f)):
    transpuesta = vectores_f[i][:, np.newaxis]
    transpuestas.append(transpuesta)

for i in range(len(transpuestas)):
    print(transpuestas[i])

[[-1]
 [-1]
 [-1]]
[[-1]
 [ 1]
 [-1]]


In [46]:
productos = []
for i in range(len(transpuestas)):
    producto = np.dot(transpuestas[i], vectores_f[i][np.newaxis, :])
    productos.append(producto)

for j in range(len(productos)):
    print(productos[j])

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[ 1 -1  1]
 [-1  1 -1]
 [ 1 -1  1]]


In [47]:
Pesos = sum(productos)

print(Pesos)

[[2 0 2]
 [0 2 0]
 [2 0 2]]


In [48]:
P_1 = np.copy(Pesos)
np.fill_diagonal(P_1, 0)

print(P_1)

[[0 0 2]
 [0 0 0]
 [2 0 0]]


In [49]:
activadas = []

def apply_activation(vector, weights):
    result = np.dot(vector, weights)
    activated_values = np.where(result > 0, 1, -1)
    
    return activated_values

for i in range(len(vectores_f)):
    activada = apply_activation(vectores_f[i], P_1)
    activadas.append(activada)


for i in range(len(activadas)):
    print(activadas[i])

[-1 -1 -1]
[-1 -1 -1]


In [50]:
def print_result(vector, weights, original):
    print("Entrada:\t", vector)
    print("Compara esta:\t", original)
    print("Con esta:\t", apply_activation(vector, weights), "\n")

In [51]:
def evaluation(ORIGINALES, PRUEBAS, P_1, CUENTA):  
    
    print("Evaluando con X_", CUENTA, "\n")

    ORIGINAL = ORIGINALES[CUENTA]
    PRUEBA = PRUEBAS[CUENTA]

    iteraciones = 1

    while (iteraciones < 16):
        
        # Imprimir iteracion
        print("Iteracion: ", iteraciones,"\t|\tCon X_", CUENTA)

        # Si es igual, imprime y termina
        if np.array_equal(PRUEBA, ORIGINAL):
            print("Fue igualito")
            print_result(PRUEBA, P_1, ORIGINAL)
            
            N_cuenta =  CUENTA + 1
            if N_cuenta < len(ORIGINALES):
                evaluation(ORIGINALES, PRUEBAS, P_1, N_cuenta)
            
            break

        # Si no es igual, sigue iterando
        print_result(PRUEBA, P_1, ORIGINAL)
        ORIGINAL = np.copy(PRUEBA)
        PRUEBA = apply_activation(PRUEBA, P_1)
        
        iteraciones += 1

In [52]:
evaluation(vectores_f, activadas, P_1, 0)

Evaluando con X_ 0 

Iteracion:  1 	|	Con X_ 0
Fue igualito
Entrada:	 [-1 -1 -1]
Compara esta:	 [-1 -1 -1]
Con esta:	 [-1 -1 -1] 

Evaluando con X_ 1 

Iteracion:  1 	|	Con X_ 1
Entrada:	 [-1 -1 -1]
Compara esta:	 [-1  1 -1]
Con esta:	 [-1 -1 -1] 

Iteracion:  2 	|	Con X_ 1
Fue igualito
Entrada:	 [-1 -1 -1]
Compara esta:	 [-1 -1 -1]
Con esta:	 [-1 -1 -1] 

