In [48]:
import numpy as np


def create_random_vector(size, vectors):
    
    vectores_f = []

    for i in range(vectors):
        vectores = np.random.choice([-1, 1], size=size)
        vectores_f.append(vectores)
    
    return vectores_f

size = 10
vectors = 2

vectores_f = create_random_vector(size, vectors)

for i in range(len(vectores_f)):
    print(vectores_f[i])

[-1 -1 -1  1  1  1 -1  1  1  1]
[-1 -1 -1  1 -1  1 -1 -1  1  1]


In [49]:
transpuestas = []
for i in range(len(vectores_f)):
    transpuesta = vectores_f[i][:, np.newaxis]
    transpuestas.append(transpuesta)

# for i in range(len(transpuestas)):
#     print(transpuestas[i])

In [50]:
productos = []
for i in range(len(transpuestas)):
    producto = np.dot(transpuestas[i], vectores_f[i][np.newaxis, :])
    productos.append(producto)

# for j in range(len(productos)):
#     print(productos[j])

In [51]:
Pesos = sum(productos)

print(Pesos)

[[ 2  2  2 -2  0 -2  2  0 -2 -2]
 [ 2  2  2 -2  0 -2  2  0 -2 -2]
 [ 2  2  2 -2  0 -2  2  0 -2 -2]
 [-2 -2 -2  2  0  2 -2  0  2  2]
 [ 0  0  0  0  2  0  0  2  0  0]
 [-2 -2 -2  2  0  2 -2  0  2  2]
 [ 2  2  2 -2  0 -2  2  0 -2 -2]
 [ 0  0  0  0  2  0  0  2  0  0]
 [-2 -2 -2  2  0  2 -2  0  2  2]
 [-2 -2 -2  2  0  2 -2  0  2  2]]


In [52]:
P_1 = np.copy(Pesos)
np.fill_diagonal(P_1, 0)

print(P_1)

[[ 0  2  2 -2  0 -2  2  0 -2 -2]
 [ 2  0  2 -2  0 -2  2  0 -2 -2]
 [ 2  2  0 -2  0 -2  2  0 -2 -2]
 [-2 -2 -2  0  0  2 -2  0  2  2]
 [ 0  0  0  0  0  0  0  2  0  0]
 [-2 -2 -2  2  0  0 -2  0  2  2]
 [ 2  2  2 -2  0 -2  0  0 -2 -2]
 [ 0  0  0  0  2  0  0  0  0  0]
 [-2 -2 -2  2  0  2 -2  0  0  2]
 [-2 -2 -2  2  0  2 -2  0  2  0]]


In [53]:
activadas = []

def apply_activation(vector, weights):
    result = np.dot(vector, weights)
    activated_values = np.where(result > 0, 1, -1)
    
    return activated_values

for i in range(len(vectores_f)):
    activada = apply_activation(vectores_f[i], P_1)
    activadas.append(activada)


for i in range(len(activadas)):
    print(activadas[i])

[-1 -1 -1  1  1  1 -1  1  1  1]
[-1 -1 -1  1 -1  1 -1 -1  1  1]


In [54]:
def print_result(vector, weights, original):
    print("Entrada:\t", vector)
    print("Original:\t", original)
    print("Resultado:\t", apply_activation(vector, weights), "\n")

In [55]:
def evaluation(ORIGINALES, PRUEBAS, P_1, CUENTA):  
    
    ORIGINAL = ORIGINALES[CUENTA]
    PRUEBA = PRUEBAS[CUENTA]

    iteraciones = 1

    while (iteraciones < 16):
        
        # Imprimir iteracion
        print("Iteracion: ", iteraciones,"\t|\tCon X_", CUENTA)

        # Si es igual, imprime y termina
        if np.array_equal(PRUEBA, ORIGINAL):
            print("Fue igualito")
            print_result(PRUEBA, P_1, ORIGINAL)
            break

        # Si no es igual, sigue iterando
        PRUEBA = apply_activation(PRUEBA, P_1)
        print_result(PRUEBA, P_1, ORIGINAL)
        
        cuenta += 1

In [56]:
for i in range(len(vectores_f)):
    evaluation(vectores_f, activadas, P_1, i)

Iteracion:  1 	|	Con X_ 0
Fue igualito
Entrada:	 [-1 -1 -1  1  1  1 -1  1  1  1]
Original:	 [-1 -1 -1  1  1  1 -1  1  1  1]
Resultado:	 [-1 -1 -1  1  1  1 -1  1  1  1] 

Iteracion:  1 	|	Con X_ 1
Fue igualito
Entrada:	 [-1 -1 -1  1 -1  1 -1 -1  1  1]
Original:	 [-1 -1 -1  1 -1  1 -1 -1  1  1]
Resultado:	 [-1 -1 -1  1 -1  1 -1 -1  1  1] 

