In [90]:
import numpy as np


def create_random_vector(size):
    A = np.random.choice([-1, 1], size=size)
    B = np.random.choice([-1, 1], size=size)
    return A, B

size = 5
A, B = create_random_vector(size)

print(A)
print(B)

[-1 -1  1  1  1]
[ 1  1 -1 -1  1]


In [91]:
At = A[:, np.newaxis]
Bt = B[:, np.newaxis]

resultA = np.dot(At, A[np.newaxis, :])
resultB = np.dot(Bt, B[np.newaxis, :])

In [92]:
Pesos = resultA + resultB

print(Pesos)

[[ 2  2 -2 -2  0]
 [ 2  2 -2 -2  0]
 [-2 -2  2  2  0]
 [-2 -2  2  2  0]
 [ 0  0  0  0  2]]


In [93]:
P_1 = np.copy(Pesos)
np.fill_diagonal(P_1, 0)

print(P_1)

[[ 0  2 -2 -2  0]
 [ 2  0 -2 -2  0]
 [-2 -2  0  2  0]
 [-2 -2  2  0  0]
 [ 0  0  0  0  0]]


In [94]:
result = np.dot(A, P_1)
print(result)

[-6 -6  6  6  0]


In [95]:
def apply_activation(vector, weights):
    result = np.dot(vector, weights)
    activated_values = np.where(result > 0, 1, -1)
    return activated_values

print(apply_activation(A, P_1))

[-1 -1  1  1 -1]


In [106]:
def print_result(vector, weights):
    print("Entrada:", vector)
    print("Resultado:", apply_activation(vector, weights))

def evaluation(ORIGINAL, PRUEBA, P_1):
    
    # Si el resultado de la prueba es igual al original
    if np.array_equal(PRUEBA, ORIGINAL):
        print("Fue igualito")
        print_result(PRUEBA, P_1)

    # Si no es igual, se hace una nueva prueba
    else:
        cuenta = 1
        while (cuenta < 16 and not np.array_equal(PRUEBA, ORIGINAL)):
            print("No fue igual, cuenta:", cuenta)
            # print_result(PRUEBA, P_1)
            print("Prueba antes:", PRUEBA)
            PRUEBA = apply_activation(PRUEBA, P_1)
            print("Prueba despues:", PRUEBA)
            cuenta += 1

        print("Fue igualito")
        print_result(PRUEBA, P_1)

evaluation(A, apply_activation(A,P_1), P_1)

No fue igual, cuenta: 1
Entrada: [-1 -1  1  1 -1]
Resultado: [-1 -1  1  1 -1]
Prueba antes: [-1 -1  1  1 -1]
Prueba despues: [-1 -1  1  1 -1]
No fue igual, cuenta: 2
Entrada: [-1 -1  1  1 -1]
Resultado: [-1 -1  1  1 -1]
Prueba antes: [-1 -1  1  1 -1]
Prueba despues: [-1 -1  1  1 -1]
No fue igual, cuenta: 3
Entrada: [-1 -1  1  1 -1]
Resultado: [-1 -1  1  1 -1]
Prueba antes: [-1 -1  1  1 -1]
Prueba despues: [-1 -1  1  1 -1]
No fue igual, cuenta: 4
Entrada: [-1 -1  1  1 -1]
Resultado: [-1 -1  1  1 -1]
Prueba antes: [-1 -1  1  1 -1]
Prueba despues: [-1 -1  1  1 -1]
No fue igual, cuenta: 5
Entrada: [-1 -1  1  1 -1]
Resultado: [-1 -1  1  1 -1]
Prueba antes: [-1 -1  1  1 -1]
Prueba despues: [-1 -1  1  1 -1]
No fue igual, cuenta: 6
Entrada: [-1 -1  1  1 -1]
Resultado: [-1 -1  1  1 -1]
Prueba antes: [-1 -1  1  1 -1]
Prueba despues: [-1 -1  1  1 -1]
No fue igual, cuenta: 7
Entrada: [-1 -1  1  1 -1]
Resultado: [-1 -1  1  1 -1]
Prueba antes: [-1 -1  1  1 -1]
Prueba despues: [-1 -1  1  1 -1]
No fue

In [102]:
count = 0
test = 2
while (test == 1 or count < 10):
    print("Prueba:", count, " Buenas:", test)
    count += 1

Prueba: 0  Buenas: 2
Prueba: 1  Buenas: 2
Prueba: 2  Buenas: 2
Prueba: 3  Buenas: 2
Prueba: 4  Buenas: 2
Prueba: 5  Buenas: 2
Prueba: 6  Buenas: 2
Prueba: 7  Buenas: 2
Prueba: 8  Buenas: 2
Prueba: 9  Buenas: 2
