In [1096]:
import numpy as np


def create_random_vector(size):
    A = np.random.choice([-1, 1], size=size)
    B = np.random.choice([-1, 1], size=size)
    return A, B

size = 5
A, B = create_random_vector(size)

print(A)
print(B)

[-1  1 -1  1 -1]
[-1  1 -1  1  1]


In [1097]:
At = A[:, np.newaxis]
Bt = B[:, np.newaxis]

resultA = np.dot(At, A[np.newaxis, :])
resultB = np.dot(Bt, B[np.newaxis, :])

In [1098]:
Pesos = resultA + resultB

print(Pesos)

[[ 2 -2  2 -2  0]
 [-2  2 -2  2  0]
 [ 2 -2  2 -2  0]
 [-2  2 -2  2  0]
 [ 0  0  0  0  2]]


In [1099]:
P_1 = np.copy(Pesos)
np.fill_diagonal(P_1, 0)

print(P_1)

[[ 0 -2  2 -2  0]
 [-2  0 -2  2  0]
 [ 2 -2  0 -2  0]
 [-2  2 -2  0  0]
 [ 0  0  0  0  0]]


In [1100]:
result = np.dot(A, P_1)
print(result)

[-6  6 -6  6  0]


In [1112]:
def apply_activation(vector, weights):
    # print("Entradita chida:\t\t", vector)
    result = np.dot(vector, weights)
    # print("Resultado de la multiplicacion:\t", result)
    activated_values = np.where(result >= 0, 1, -1)
    return activated_values

print(apply_activation(A, P_1))

[-1  1 -1  1  1]


In [1102]:
def print_result(vector, weights, original):
    print("Entrada:\t", vector)
    print("Original:\t", original)
    print("Resultado:\t", apply_activation(vector, weights), "\n")

# def evaluation(ORIGINAL, PRUEBA, P_1):  
    
#     cuenta = 1

#     while (cuenta < 16):
        
#         # Imprimir iteracion
#         print("Iteracion: ", cuenta)

#         # Si es igual, imprime y termina
#         if np.array_equal(PRUEBA, ORIGINAL):
#             print("Fue igualito")
#             print_result(PRUEBA, P_1, ORIGINAL)
#             break

#         # Si no es igual, sigue iterando
#         PRUEBA = apply_activation(PRUEBA, P_1)
#         print_result(PRUEBA, P_1, ORIGINAL)


#         # print_result(ORIGINAL, P_1)
        
#         cuenta += 1

# evaluation(A, apply_activation(A,P_1), P_1)

In [1103]:
cuentaa = 0

Pruebita = apply_activation(A, P_1)

print("Pruebita inicial:\t", Pruebita)
print("Original:\t\t", A, "\n")

while (cuentaa < 15):

    print("Iteracion: ", cuentaa)

    if np.array_equal(Pruebita, A):
        print("Fue igualito")
        print_result(Pruebita, P_1, A)
        break

    print("No fue igual")
    Pruebita = apply_activation(Pruebita, P_1)
    print_result(Pruebita, P_1, A)
    cuentaa += 1

Pruebita inicial:	 [-1  1 -1  1  1]
Original:		 [-1  1 -1  1 -1] 

Iteracion:  0
Entrada:	 [-1  1 -1  1  1]
Original:	 [-1  1 -1  1 -1]
Resultado:	 [-1  1 -1  1  1] 

Iteracion:  1
Entrada:	 [-1  1 -1  1  1]
Original:	 [-1  1 -1  1 -1]
Resultado:	 [-1  1 -1  1  1] 

Iteracion:  2
Entrada:	 [-1  1 -1  1  1]
Original:	 [-1  1 -1  1 -1]
Resultado:	 [-1  1 -1  1  1] 

Iteracion:  3
Entrada:	 [-1  1 -1  1  1]
Original:	 [-1  1 -1  1 -1]
Resultado:	 [-1  1 -1  1  1] 

Iteracion:  4
Entrada:	 [-1  1 -1  1  1]
Original:	 [-1  1 -1  1 -1]
Resultado:	 [-1  1 -1  1  1] 

Iteracion:  5
Entrada:	 [-1  1 -1  1  1]
Original:	 [-1  1 -1  1 -1]
Resultado:	 [-1  1 -1  1  1] 

Iteracion:  6
Entrada:	 [-1  1 -1  1  1]
Original:	 [-1  1 -1  1 -1]
Resultado:	 [-1  1 -1  1  1] 

Iteracion:  7
Entrada:	 [-1  1 -1  1  1]
Original:	 [-1  1 -1  1 -1]
Resultado:	 [-1  1 -1  1  1] 

Iteracion:  8
Entrada:	 [-1  1 -1  1  1]
Original:	 [-1  1 -1  1 -1]
Resultado:	 [-1  1 -1  1  1] 

Iteracion:  9
Entrada:	 [-1  1 -1

In [1117]:
import numpy as np

print("Pesos:\n", P_1, "\n")

result = apply_activation(A, P_1)
print("Resultado de multiplicar X1 con P_1:\n", result)

result2 = apply_activation( apply_activation(A,P_1) , P_1)
print("Resultado de multiplicar R_1 con P_1:\n", result2)

Pesos:
 [[ 0 -2  2 -2  0]
 [-2  0 -2  2  0]
 [ 2 -2  0 -2  0]
 [-2  2 -2  0  0]
 [ 0  0  0  0  0]] 

Resultado de multiplicar X1 con P_1:
 [-1  1 -1  1  1]
Resultado de multiplicar R_1 con P_1:
 [-1  1 -1  1  1]
