In [90]:
import numpy as np


def create_random_vector(size):
    A = np.random.choice([-1, 1], size=size)
    B = np.random.choice([-1, 1], size=size)
    return A, B

size = 5
A, B = create_random_vector(size)

print(A)
print(B)

[-1 -1  1  1  1]
[ 1  1 -1 -1  1]


In [91]:
At = A[:, np.newaxis]
Bt = B[:, np.newaxis]

resultA = np.dot(At, A[np.newaxis, :])
resultB = np.dot(Bt, B[np.newaxis, :])

In [92]:
Pesos = resultA + resultB

print(Pesos)

[[ 2  2 -2 -2  0]
 [ 2  2 -2 -2  0]
 [-2 -2  2  2  0]
 [-2 -2  2  2  0]
 [ 0  0  0  0  2]]


In [93]:
P_1 = np.copy(Pesos)
np.fill_diagonal(P_1, 0)

print(P_1)

[[ 0  2 -2 -2  0]
 [ 2  0 -2 -2  0]
 [-2 -2  0  2  0]
 [-2 -2  2  0  0]
 [ 0  0  0  0  0]]


In [94]:
result = np.dot(A, P_1)
print(result)

[-6 -6  6  6  0]


In [95]:
def apply_activation(vector, weights):
    result = np.dot(vector, weights)
    activated_values = np.where(result > 0, 1, -1)
    return activated_values

print(apply_activation(A, P_1))

[-1 -1  1  1 -1]


In [96]:
def print_result(vector, weights):
    print("Entrada:", vector)
    print("Resultado:", apply_activation(vector, weights))
    print()

PRUEBA = apply_activation(A, P_1)

if np.array_equal(PRUEBA, A):
    print("Fue igualito")
    print_result(A, P_1)
    print("Ahora el B")
    print_result(B, P_1)

cuenta = 0
if (not np.array_equal(PRUEBA, A) or cuenta == 15):
        print("No fue igual")
        print_result(PRUEBA, P_1)
        PRUEBA = apply_activation(PRUEBA, P_1)
        cuenta += 1

No fue igual
Entrada: [-1 -1  1  1 -1]
Resultado: [-1 -1  1  1 -1]

