In [9]:
import numpy as np
def create_custom_vectors():
    while True:
        num_vectors = int(input("No. de vectores: "))
        if 3 <= num_vectors <= 5:
            break
        else:
            print("Solo se permiten valores entre 3 y 5.")
    size = int(input("Tamaño: "))
    
    vectors = []
    for i in range(num_vectors):
        vector = []
        print(f"Ingrese el elemento del vector{i+1}: ( 1 o -1):")
        for j in range(size):
            while True:
                value = int(input(f"Elemento {j+1}: "))
                if value in [-1, 1]:
                    vector.append(value)
                    break
                else:
                    print("Valor invalido")
        vectors.append(np.array(vector))
    return vectors


vectores_f = create_custom_vectors()



Ingrese el elemento del vector1: ( 1 o -1):
Ingrese el elemento del vector2: ( 1 o -1):
Ingrese el elemento del vector3: ( 1 o -1):


In [3]:
transpuestas = []
for i in range(len(vectores_f)):
    transpuesta = vectores_f[i][:, np.newaxis]
    transpuestas.append(transpuesta)

# for i in range(len(transpuestas)):
#     print(transpuestas[i])

In [4]:
productos = []
for i in range(len(transpuestas)):
    producto = np.dot(transpuestas[i], vectores_f[i][np.newaxis, :])
    productos.append(producto)

# for j in range(len(productos)):
#     print(productos[j])

In [5]:
Pesos = sum(productos)

print(Pesos)

[[ 3  1  1 -1]
 [ 1  3  3 -3]
 [ 1  3  3 -3]
 [-1 -3 -3  3]]


In [6]:
P_1 = np.copy(Pesos)
np.fill_diagonal(P_1, 0)

print(P_1)

[[ 0  1  1 -1]
 [ 1  0  3 -3]
 [ 1  3  0 -3]
 [-1 -3 -3  0]]


In [122]:
activadas = []

def apply_activation(vector, weights):
    result = np.dot(vector, weights)
    activated_values = np.where(result > 0, 1, -1)
    
    return activated_values

for i in range(len(vectores_f)):
    activada = apply_activation(vectores_f[i], P_1)
    activadas.append(activada)


for i in range(len(activadas)):
    print(activadas[i])

[-1  1 -1]
[-1  1 -1]


In [123]:
def print_result(vector, weights, original):
    print("Entrada:\t", vector)
    print("Original:\t", original)
    print("Resultado:\t", apply_activation(vector, weights), "\n")

In [126]:
def evaluation(ORIGINALES, PRUEBAS, P_1, CUENTA):  
    
    ORIGINAL = ORIGINALES[CUENTA]
    PRUEBA = PRUEBAS[CUENTA]

    iteraciones = 1

    while (iteraciones < 16):
        
        # Imprimir iteracion
        print("Iteracion: ", iteraciones,"\t|\tCon X_", CUENTA)

        # Si es igual, imprime y termina
        if np.array_equal(PRUEBA, ORIGINAL):
            print("Fue igualito")
            print_result(PRUEBA, P_1, ORIGINAL)
            break

        # Si no es igual, sigue iterando
        PRUEBA = apply_activation(PRUEBA, P_1)
        print_result(PRUEBA, P_1, ORIGINAL)
        
        iteraciones += 1

In [127]:
for i in range(len(vectores_f)):
    # evaluation(vectores_f, activadas, P_1, i)
    # print("Iteracion: ", i)
    # print("Original: ", vectores_f[i])
    # print("Resultado: ", activadas[i])
    # print("\n")
    evaluation(vectores_f, activadas, P_1, i)


Iteracion:  1 	|	Con X_ 0
Fue igualito
Entrada:	 [-1  1 -1]
Original:	 [-1  1 -1]
Resultado:	 [-1  1 -1] 

Iteracion:  1 	|	Con X_ 1
Entrada:	 [-1  1 -1]
Original:	 [-1  1  1]
Resultado:	 [-1  1 -1] 

Iteracion:  2 	|	Con X_ 1
Entrada:	 [-1  1 -1]
Original:	 [-1  1  1]
Resultado:	 [-1  1 -1] 

Iteracion:  3 	|	Con X_ 1
Entrada:	 [-1  1 -1]
Original:	 [-1  1  1]
Resultado:	 [-1  1 -1] 

Iteracion:  4 	|	Con X_ 1
Entrada:	 [-1  1 -1]
Original:	 [-1  1  1]
Resultado:	 [-1  1 -1] 

Iteracion:  5 	|	Con X_ 1
Entrada:	 [-1  1 -1]
Original:	 [-1  1  1]
Resultado:	 [-1  1 -1] 

Iteracion:  6 	|	Con X_ 1
Entrada:	 [-1  1 -1]
Original:	 [-1  1  1]
Resultado:	 [-1  1 -1] 

Iteracion:  7 	|	Con X_ 1
Entrada:	 [-1  1 -1]
Original:	 [-1  1  1]
Resultado:	 [-1  1 -1] 

Iteracion:  8 	|	Con X_ 1
Entrada:	 [-1  1 -1]
Original:	 [-1  1  1]
Resultado:	 [-1  1 -1] 

Iteracion:  9 	|	Con X_ 1
Entrada:	 [-1  1 -1]
Original:	 [-1  1  1]
Resultado:	 [-1  1 -1] 

Iteracion:  10 	|	Con X_ 1
Entrada:	 [-1  1 -1]