In [20]:
import numpy as np


def create_random_vector(size, vectors):
    
    vectores_f = []

    for i in range(vectors):
        vectores = np.random.choice([-1, 1], size=size)
        vectores_f.append(vectores)
    
    return vectores_f

size = 10
vectors = 2

vectores_f = create_random_vector(size, vectors)

for i in range(len(vectores_f)):
    print(vectores_f[i])

[ 1  1 -1 -1 -1  1 -1  1 -1  1]
[ 1 -1 -1  1  1  1 -1 -1 -1  1]


In [21]:
transpuestas = []
for i in range(len(vectores_f)):
    transpuesta = vectores_f[i][:, np.newaxis]
    transpuestas.append(transpuesta)

# for i in range(len(transpuestas)):
#     print(transpuestas[i])

In [22]:
productos = []
for i in range(len(transpuestas)):
    producto = np.dot(transpuestas[i], vectores_f[i][np.newaxis, :])
    productos.append(producto)

# for j in range(len(productos)):
#     print(productos[j])

[[ 1  1 -1 -1 -1  1 -1  1 -1  1]
 [ 1  1 -1 -1 -1  1 -1  1 -1  1]
 [-1 -1  1  1  1 -1  1 -1  1 -1]
 [-1 -1  1  1  1 -1  1 -1  1 -1]
 [-1 -1  1  1  1 -1  1 -1  1 -1]
 [ 1  1 -1 -1 -1  1 -1  1 -1  1]
 [-1 -1  1  1  1 -1  1 -1  1 -1]
 [ 1  1 -1 -1 -1  1 -1  1 -1  1]
 [-1 -1  1  1  1 -1  1 -1  1 -1]
 [ 1  1 -1 -1 -1  1 -1  1 -1  1]]
[[ 1 -1 -1  1  1  1 -1 -1 -1  1]
 [-1  1  1 -1 -1 -1  1  1  1 -1]
 [-1  1  1 -1 -1 -1  1  1  1 -1]
 [ 1 -1 -1  1  1  1 -1 -1 -1  1]
 [ 1 -1 -1  1  1  1 -1 -1 -1  1]
 [ 1 -1 -1  1  1  1 -1 -1 -1  1]
 [-1  1  1 -1 -1 -1  1  1  1 -1]
 [-1  1  1 -1 -1 -1  1  1  1 -1]
 [-1  1  1 -1 -1 -1  1  1  1 -1]
 [ 1 -1 -1  1  1  1 -1 -1 -1  1]]


In [23]:
Pesos = sum(productos)

print(Pesos)

[[ 2  0 -2  0  0  2 -2  0 -2  2]
 [ 0  2  0 -2 -2  0  0  2  0  0]
 [-2  0  2  0  0 -2  2  0  2 -2]
 [ 0 -2  0  2  2  0  0 -2  0  0]
 [ 0 -2  0  2  2  0  0 -2  0  0]
 [ 2  0 -2  0  0  2 -2  0 -2  2]
 [-2  0  2  0  0 -2  2  0  2 -2]
 [ 0  2  0 -2 -2  0  0  2  0  0]
 [-2  0  2  0  0 -2  2  0  2 -2]
 [ 2  0 -2  0  0  2 -2  0 -2  2]]


In [24]:
P_1 = np.copy(Pesos)
np.fill_diagonal(P_1, 0)

print(P_1)

[[ 0  0 -2  0  0  2 -2  0 -2  2]
 [ 0  0  0 -2 -2  0  0  2  0  0]
 [-2  0  0  0  0 -2  2  0  2 -2]
 [ 0 -2  0  0  2  0  0 -2  0  0]
 [ 0 -2  0  2  0  0  0 -2  0  0]
 [ 2  0 -2  0  0  0 -2  0 -2  2]
 [-2  0  2  0  0 -2  0  0  2 -2]
 [ 0  2  0 -2 -2  0  0  0  0  0]
 [-2  0  2  0  0 -2  2  0  0 -2]
 [ 2  0 -2  0  0  2 -2  0 -2  0]]


In [34]:
def apply_activation(vector, weights):
    result = np.dot(vector, weights)
    activated_values = np.where(result > 0, 1, -1)
    
    return activated_values

print(apply_activation(vectores_f[0], P_1),"\n",apply_activation(vectores_f[1], P_1))

[ 1  1 -1 -1 -1  1 -1  1 -1  1] 
 [ 1 -1 -1  1  1  1 -1 -1 -1  1]


In [26]:
def print_result(vector, weights, original):
    print("Entrada:\t", vector)
    print("Original:\t", original)
    print("Resultado:\t", apply_activation(vector, weights), "\n")

In [27]:
def evaluation(ORIGINAL, PRUEBA, P_1):  
    
    cuenta = 1

    while (cuenta < 16):
        
        # Imprimir iteracion
        print("Iteracion: ", cuenta)

        # Si es igual, imprime y termina
        if np.array_equal(PRUEBA, ORIGINAL):
            print("Fue igualito")
            print_result(PRUEBA, P_1, ORIGINAL)
            # evaluation(B, apply_activation(B, P_1), P_1)
            break

        # Si no es igual, sigue iterando
        PRUEBA = apply_activation(PRUEBA, P_1)
        print_result(PRUEBA, P_1, ORIGINAL)
        
        cuenta += 1

evaluation(vectores_f[0], apply_activation(vectores_f[0],P_1), P_1)

Iteracion:  1
Fue igualito
Entrada:	 [ 1  1 -1 -1 -1  1 -1  1 -1  1]
Original:	 [ 1  1 -1 -1 -1  1 -1  1 -1  1]
Resultado:	 [ 1  1 -1 -1 -1  1 -1  1 -1  1] 



In [28]:
# cuentaa = 0

# Pruebita = apply_activation(A, P_1)

# # print("Pruebita inicial:\t", Pruebita)
# # print("Original:\t\t", A, "\n")

# while (cuentaa < 15):

#     print("Iteracion: ", cuentaa)

#     if np.array_equal(Pruebita, A):
#         print("Fue igualito")
#         print_result(Pruebita, P_1, A)
#         apply_activation(B, P_1)
#         break

#     print("No fue igual")
#     Pruebita = apply_activation(Pruebita, P_1)
#     print_result(Pruebita, P_1, A)
#     cuentaa += 1

In [29]:
# import numpy as np

# print("Pesos:\n", P_1, "\n")

# result = apply_activation(A, P_1)
# print("Resultado de multiplicar X1 con P_1:\n", result)

# result2 = apply_activation( apply_activation(A,P_1) , P_1)
# print("Resultado de multiplicar R_1 con P_1:\n", result2)